respect log level
beapplied/applied-logger pull request #18
Opened 2020-02-18 22:37 UTC by richmarr

Currently passing an error into `logger.warn` will result in `status:"ERROR"`

This change allows `logger.warn` to respect the log level specified by the client code

2020-02-19 19:40 UTC, kiedunne approved these changes

2020-02-19 19:40 UTC, kiedunne commented on src/utils.test.js
>  })
new  line

2020-02-20 07:58 UTC, hewIngram requested changes

2020-02-20 07:58 UTC, hewIngram commented on src/config.js
> +    ERROR: {
Can you add a test for this change - i.e a test that would have failed before and is now passing

2020-02-24 16:13 UTC, hewIngram approved these changes

2020-03-12 09:41 UTC, merged